### PR TITLE
Restrict SCOPE and fix yq command

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

Restrict SCOPE and fix yq command

---

**Related issue :**

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
xref: https://goc.egi.eu/portal/index.php?Page_Type=Downtime&id=35925

**Comment by enolfc** [comment]
We can ignore the validation test as ops portal is not available

**Review by enolfc — APPROVED** [review]
LGTM

**Comment by enolfc** [comment]
Merging bypassing the Validation as it's caused by ops portal downtime

**Pull request merged**
