### PR TITLE
Add vo icecube.

### PR DESCRIPTION
**Pull request by rosinec**
Add support for VO:icecube within CESNET-MCC.

### CODE REVIEW

**Review by enolfc — COMMENTED** [review]
Thanks @rosinec!
Could you confirm which is the mapping you are using for icecube?

**Comment by rosinec** [comment]
Hello, can you elaborate, what do you need specifically? I am newbie with EGI FedCloud, sorry :).

**Comment by enolfc** [comment]
Hi, no worries.
I'm adding the mapping in #156. This is meant to be available for people configuring the VO to add it to the Keystone configuration and we added a test to ensure is there. Once merged, we merge this one.

**Review by enolfc — APPROVED** [review]
LGTM!

**Pull request merged**
