### PR TITLE
Update ILIFU-UCT.yaml

### PR DESCRIPTION
**Pull request by daikema**
Ilifu Openstack is now accessible at https://openstack.ilifu.ac.za rather than at https://dashboard2.ilifu.ac.za.  Though the old dashboard2 DNS entry still points to the same IP as openstack.ilifu.ac.za use of the old hostname may result in an invalid redirect error when using OIDC authentication.

### CODE REVIEW

**Comment by enolfc** [comment]
The information added here should be consistent with GOCDB:
https://github.com/EGI-Federation/fedcloud-catchall-operations/actions/runs/6250225882/job/16968597923?pr=305#step:6:49

The endpoint needs to be updated there beforehand

**Comment by daikema** [comment]
I've now made the GOCDB update

**Review by enolfc — COMMENTED** [review]
👍

**Review by enolfc — APPROVED** [review]

**Comment by enolfc** [comment]
Validation error should be gone after merging #303

**Pull request merged**
