### PR TITLE
Update INFN-CLOUD-CNAF with ESCAPE info

### PR DESCRIPTION
**Pull request by caifti**
# Summary

---

**Related issue :**

### CODE REVIEW

**Comment by andrea-manzi** [comment]
@caifti i managed to get the project id and created a PR before yours yesterday https://github.com/EGI-Federation/fedcloud-catchall-operations/pull/213 which we have just merged, sorry for this  and thanks for your availability!

**Comment by caifti** [comment]
> 

then you forgot to let me know before I start working.

**Comment by andrea-manzi** [comment]
really sorry for this..i will ask the admin to close the PR as i cannot do it myself

**Comment by enolfc** [comment]
No need for this anymore

**Pull request closed without merging**
