### PR TITLE
dteam VO is no longer required for EGI cloud sites

### PR DESCRIPTION
**Pull request by freznicek**
# Summary

Dropping dteam VO from CESNET-MCCG2 as this VO is no longer needed.

### CODE REVIEW

**Comment by enolfc** [comment]
Trying to solve issues in #384 before merging.
I have found Keystone gives a timeout and eventually Unauthorized when using my Check-in token, when I was expecting to get authenticated
```
$ curl -X POST https://identity.brno.openstack.cloud.e-infra.cz/v3/OS-FEDERATION/identity_providers/egi.eu/protocols/openid/auth -H "Authorization: Bearer XXXX"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
```

Could you check if there is an issue there?

**Comment by freznicek** [comment]
> https://identity.brno.openstack.cloud.e-infra.cz/v3/OS-FEDERATION/identity_providers/egi.eu/protocols/openid/auth

I will doublecheck, are you exclusively using this identity 529a...3907@egi.eu for CESNET-MCCG2?

I'll keep you updated.

**Comment by enolfc** [comment]
> I will doublecheck, are you exclusively using this identity [529a...3907@egi.eu](mailto:529a...3907@egi.eu) for CESNET-MCCG2?

yes that's me

**Comment by freznicek** [comment]
Sorry for inconvenience @enolfc , issue has been fixed.
Above POST calls are returning valid response now.

May I ask you for ack that you see it functional now?

**Comment by enolfc** [comment]
> 
> May I ask you for ack that you see it functional now?

It works now. 

I see in my tests, the `biomed` project is also enabled (although it does not have the `VO` property). Could you add it to this PR so we have it included as well?

Thanks

**Comment by freznicek** [comment]
> I see in my tests, the `biomed` project is also enabled (although it does not have the `VO` property). Could you add it to this PR so we have it included as well?
> 
> Thanks

Indeed, PR updated and project properly annotated (VO, acounting:VO).

**Review by enolfc — APPROVED** [review]
Thanks!

**Pull request merged**
