### PR TITLE
Remove vo.e-rihs.eu from list

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

---

**Related issue :**

### CODE REVIEW

**Review by sebastian-luna-valero — APPROVED** [review]

**Comment by enolfc** [comment]
@freznicek what's the actual name of the `envri-vre` VO?

**Comment by freznicek** [comment]
> `envri-vre`

Last Tuesday I confirmed with @mKlaris (K. Moravcová) that VO envri-vre should be `Virtual Research Environment (VRE) for ENVRI-Hub NEXT Project. Project receives funding from the European Union's Horizon Europe research and innovation programme under grant agreement No 101131141.` I've got following entitlement from her `urn:mace:egi.eu:group:envri-vre:role=vm_operator#aai.egi.eu`.

Let me know if there is mismatch. Also I'd like to know the independent way where I can cross-check the correctness. Do you know how?

**Comment by enolfc** [comment]
> > `envri-vre`
> 
> Last Tuesday I confirmed with @mKlaris that VO envri-vre should be `Virtual Research Environment (VRE) for ENVRI-Hub NEXT Project. Project receives funding from the European Union's Horizon Europe research and innovation programme under grant agreement No 101131141.` I've got following entitlement from her `urn:mace:egi.eu:group:envri-vre:role=vm_operator#aai.egi.eu`.
> 
> Let me know if there is mismatch. Also I'd like to know the independent way where I can cross-check the correctness. Do you know how?

We are assuming the VOs are registered in the operations portal: https://operations-portal.egi.eu/vo/a/list, `envri-vre` is not there, although there is 
[vo.envrihub.eu](https://operations-portal.egi.eu/vo/view/voname/vo.envrihub.eu) and [vo.envri-fair.eu](https://operations-portal.egi.eu/vo/view/voname/vo.envri-fair.eu). Where does this entitlement come from? is this managed in Perun and maybe we miss the registration in the ops portal?

**Comment by mKlaris** [comment]
> 
> We are assuming the VOs are registered in the operations portal: https://operations-portal.egi.eu/vo/a/list, `envri-vre` is not there, although there is [vo.envrihub.eu](https://operations-portal.egi.eu/vo/view/voname/vo.envrihub.eu) and [vo.envri-fair.eu](https://operations-portal.egi.eu/vo/view/voname/vo.envri-fair.eu). Where does this entitlement come from? is this managed in Perun and maybe we miss the registration in the ops portal?

Hi Enol,
there is GGUS ticket related to envri-vre VO request - https://ggus.eu/index.php?mode=ticket_info&ticket_id=168562

**Comment by enolfc** [comment]
I removed the error in case the VO is not in the ops portal to avoid having the checks failing for now.

**Pull request merged**
