### PR TITLE
Update VO information

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Get ready for validation of the VO information
Update all known VOs for now

---

**Related issue :**

### CODE REVIEW

**Review by gwarf — DISMISSED** [review]
LGTM

**Comment by gwarf** [comment]
Linting error are due to https://github.com/github/super-linter/issues/2128

**Comment by enolfc** [comment]
> Linting errors are due to [github/super-linter#2128](https://github.com/github/super-linter/issues/2128)

Should we try to apply this: https://github.com/github/super-linter/issues/2128#issuecomment-968202245 or wait untill they fix the missing image?

**Comment by gwarf** [comment]
It was reported last Friday so I guess it could be fixed "soon". Basically it depends on the urgency level for merging this. I leave it up to you, both are fine with me.

**Comment by gwarf** [comment]
@enolfc you won a few new points to be addressed :)

**Comment by enolfc** [comment]
> @enolfc you won a few new points to be addressed :)

wow, this linter can be picky:
>  23:31  ✓ error  Incorrect usage of the term: “repo”, use “repository” instead  terminology

**Comment by gwarf** [comment]
> > @enolfc you won a few new points to be addressed :)
> 
> wow, this linter can be picky:
> 
> > 23:31  ✓ error  Incorrect usage of the term: “repo”, use “repository” instead  terminology

Yes but I tend to agree with him :)

**Review by gwarf — APPROVED** [review]
LGTM

**Pull request merged**
