### PR TITLE
Add vo.eurosea.marine.ie to WALTON-CLOUD

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
# Summary

Enrollment URL for service account:  https://aai.egi.eu/registry/co_petitions/start/coef:636

---

**Related issue :**

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Same issue as in: https://github.com/EGI-Federation/fedcloud-catchall-operations/pull/294

```
VO vo.binare-oy.eu not configured
```

Maybe I should also revert https://github.com/EGI-Federation/fedcloud-catchall-operations/pull/295/commits/53483e89483aaa9721e510a22f2dba2ecd2c9eb9 to handle it in a separate PR?

**Comment by enolfc** [comment]
VO membership requested.

**Comment by sebastian-luna-valero** [comment]
Approved.

**Review by enolfc — APPROVED** [review]
👍

**Comment by enolfc** [comment]
Merging as errors are well-known and harmless.

**Pull request merged**
