### PR TITLE
VO cleanup

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

- Add some missing VOs
- Add expiry information about the membership so we can check that automatically (not used at the moment)
- Fix validation for VO subgroups

---

**Related issue :**

### CODE REVIEW

**Comment by enolfc** [comment]
I keep adding VOs as they come...

**Comment by enolfc** [comment]
@gwarf , @CatalinCondurache could you take a look?

**Comment by enolfc** [comment]
I'm using superpowers to merge this one... need to have sites working 🤷

**Comment by gwarf** [comment]
> I'm using superpowers to merge this one... need to have sites working 🤷

Sorry we were both at a F2F meeting and missed it.

**Pull request merged**
